s = 'abcdefghijk'
s = 'abcdefghijk'
print(s[3:6], end = " ")
print(s[:6], end = " ")
print(s[3:], end = " ")
print(s[::-1], end = " ")
print(s[-3:], end = " ")
print(s[:-6], end = " ")
print(s[-1:-0:-2], end = " ")